# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foods_name', models.CharField(max_length=20, verbose_name='菜名')),
                ('foods_type', models.CharField(choices=[('冷菜', '冷菜'), ('热炒菜', '热炒菜'), ('干锅类', '干锅类'), ('锅仔类', '锅仔类'), ('汤类', '汤类')], max_length=20, verbose_name='菜品类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('username', models.CharField(max_length=20, verbose_name='点单人姓名')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '去点菜',
                'verbose_name_plural': '去点菜',
                'ordering': ['-add_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='dinner',
            options={'ordering': ['-add_time'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
    ]
