# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160328_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=200, verbose_name='分支名称')),
                ('branch_type', models.CharField(choices=[('GameSupport', 'GameSupport'), ('GameGateway', 'GameGateway'), ('GameAPI', 'GameAPI')], max_length=20, verbose_name='分支类型')),
                ('author', models.CharField(max_length=20, verbose_name='部署作者')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '部署JAVA环境',
                'verbose_name': '部署JAVA环境',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Php',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=200, verbose_name='分支名称')),
                ('environment_type', models.CharField(choices=[('pc', 'pc'), ('wap', 'wap'), ('admin', 'admin'), ('ios', 'ios')], max_length=20, verbose_name='环境类型')),
                ('environment_num', models.IntegerField(default=0, verbose_name='环境编号')),
                ('author', models.CharField(max_length=20, verbose_name='部署作者')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '部署PHP环境',
                'verbose_name': '部署PHP环境',
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='UpdateAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=20, verbose_name='用户名或游戏id')),
                ('amount_type', models.CharField(choices=[('1', '挺豆'), ('2', 'T点'), ('3', 'T币'), ('4', '彩金')], max_length=20, verbose_name='金额类型')),
                ('amount', models.CharField(max_length=20, verbose_name='金额')),
                ('author', models.CharField(max_length=20, verbose_name='操作人')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '更改测试账号余额',
                'verbose_name': '更改测试账号余额',
                'ordering': ['-add_time'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
